/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffddb8",
        "surface-container-low": "#1b1b23",
        "surface-dim": "#13131b",
        "secondary-container": "#00a572",
        "inverse-surface": "#e4e1ed",
        "on-surface": "#e4e1ed",
        "on-tertiary": "#472a00",
        "secondary-fixed-dim": "#4edea3",
        "error-container": "#93000a",
        "on-surface-variant": "#c7c4d7",
        "inverse-primary": "#494bd6",
        "on-secondary-fixed-variant": "#005236",
        "on-error": "#690005",
        "surface-variant": "#34343d",
        "on-background": "#e4e1ed",
        "surface-container-high": "#292932",
        "surface-container-highest": "#34343d",
        "primary-fixed-dim": "#c0c1ff",
        "on-tertiary-container": "#3e2400",
        "on-primary-fixed": "#07006c",
        "secondary-fixed": "#6ffbbe",
        "tertiary-container": "#ca8100",
        "surface-container-lowest": "#0d0d15",
        "background": "#13131b",
        "on-secondary": "#003824",
        "outline": "#908fa0",
        "inverse-on-surface": "#303038",
        "primary-fixed": "#e1e0ff",
        "on-error-container": "#ffdad6",
        "primary": "#c0c1ff",
        "primary-container": "#8083ff",
        "surface-container": "#1f1f27",
        "outline-variant": "#464554",
        "tertiary-fixed-dim": "#ffb95f",
        "secondary": "#4edea3",
        "error": "#ffb4ab",
        "on-secondary-container": "#00311f",
        "on-primary": "#1000a9",
        "on-tertiary-fixed-variant": "#653e00",
        "on-tertiary-fixed": "#2a1700",
        "surface": "#13131b",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-secondary-fixed": "#002113",
        "surface-tint": "#c0c1ff",
        "on-primary-container": "#0d0096",
        "surface-bright": "#393841",
        "tertiary": "#ffb95f",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "base": "4px",
        "xl": "64px",
        "xs": "8px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "md": "24px",
        "gutter": "24px",
        "lg": "40px",
        "sm": "16px",
      },
      fontFamily: {
        "headline-md": ["Sora", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Sora", "sans-serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Sora", "sans-serif"],
        "headline-sm": ["Sora", "sans-serif"],
        "display-lg": ["Sora", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        sans: ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
