import json
import logging
import os
import shutil
import subprocess
import threading
import uuid
from pathlib import Path

from app.core.config import settings
from app.db.session import SessionLocal
from app.models.media_asset import MediaAsset, MediaAssetStatus
from app.services import storage_service

logger = logging.getLogger(__name__)

# Single concurrent conversion to prevent CPU starvation on API request threads
_PRESENTATION_SEMAPHORE = threading.Semaphore(1)


class PresentationError(Exception):
    def __init__(self, message: str, status_code: int = 500) -> None:
        super().__init__(message)
        self.message = message
        self.status_code = status_code


def create_presentation_scratch_dir() -> Path:
    """Creates a clean per-job scratch directory for presentation conversion."""
    base = Path(settings.presentation_temp_dir)
    base.mkdir(parents=True, exist_ok=True)
    scratch = base / uuid.uuid4().hex
    scratch.mkdir(parents=True, exist_ok=False)
    return scratch


def cleanup_presentation_dir(path: Path) -> None:
    """Removes temporary scratch files."""
    if path.exists() and path.is_dir():
        shutil.rmtree(path, ignore_errors=True)


def convert_presentation_to_pdf(input_path: Path, output_dir: Path) -> Path:
    """Converts a PPT/PPTX presentation to PDF using headless LibreOffice."""
    if input_path.suffix.lower() == ".pdf":
        return input_path

    # Find LibreOffice binary
    office_bin = shutil.which("libreoffice") or shutil.which("soffice")
    if not office_bin:
        # Check standard Windows paths if on Windows
        for win_path in [
            r"C:\Program Files\LibreOffice\program\soffice.exe",
            r"C:\Program Files (x86)\LibreOffice\program\soffice.exe",
        ]:
            if os.path.exists(win_path):
                office_bin = win_path
                break

    if not office_bin:
        raise PresentationError(
            "LibreOffice is not installed on the server for PPT-to-PDF conversion. "
            "Please ensure LibreOffice is available in the deployment environment."
        )

    cmd = [
        office_bin,
        "--headless",
        "--invisible",
        "--nologo",
        "--nofirststartwizard",
        "--convert-to",
        "pdf",
        "--outdir",
        str(output_dir),
        str(input_path),
    ]

    try:
        subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=settings.presentation_conversion_timeout,
            check=True,
        )
    except subprocess.TimeoutExpired as exc:
        raise PresentationError("Presentation conversion timed out.") from exc
    except subprocess.CalledProcessError as exc:
        logger.error("LibreOffice conversion failed: stdout=%s stderr=%s", exc.stdout, exc.stderr)
        raise PresentationError(f"Failed to convert presentation to PDF: {exc.stderr or exc.stdout}") from exc

    expected_pdf = output_dir / f"{input_path.stem}.pdf"
    if not expected_pdf.exists():
        pdfs = list(output_dir.glob("*.pdf"))
        if pdfs:
            return pdfs[0]
        raise PresentationError("Converted PDF file was not generated by LibreOffice.")

    return expected_pdf


def extract_slide_images(pdf_path: Path, output_dir: Path, dpi: int = 150) -> tuple[list[Path], list[Path]]:
    """Extracts high-resolution slide PNG images (150 DPI) and thumbnail PNG images (50 DPI) from a PDF.
    PyMuPDF (fitz) is imported lazily inside this function to prevent top-level import crashes.
    """
    try:
        import fitz
    except ImportError:
        raise PresentationError(
            "PyMuPDF ('fitz') is not installed on the server for slide extraction."
        )

    slide_paths: list[Path] = []
    thumb_paths: list[Path] = []

    slides_dir = output_dir / "slides"
    thumbs_dir = output_dir / "thumbs"
    slides_dir.mkdir(parents=True, exist_ok=True)
    thumbs_dir.mkdir(parents=True, exist_ok=True)

    doc = fitz.open(str(pdf_path))
    try:
        for page_idx in range(len(doc)):
            page = doc[page_idx]
            slide_num = page_idx + 1

            # High-res slide image (PNG for crisp classroom text and diagram rendering)
            pix = page.get_pixmap(dpi=dpi)
            slide_file = slides_dir / f"slide_{slide_num:03d}.png"
            pix.save(str(slide_file))
            slide_paths.append(slide_file)

            # Low-res thumbnail
            thumb_pix = page.get_pixmap(dpi=50)
            thumb_file = thumbs_dir / f"thumb_{slide_num:03d}.png"
            thumb_pix.save(str(thumb_file))
            thumb_paths.append(thumb_file)
    finally:
        doc.close()

    return slide_paths, thumb_paths


def _set_stage(db, asset: MediaAsset, stage: str) -> None:
    asset.processing_stage = stage
    db.commit()


def process_uploaded_presentation(media_asset_id: int, file_path: str, scratch_dir: str) -> None:
    """Background worker that converts PPT/PPTX to PDF, generates slide PNG images and thumbnails,
    uploads everything to MinIO, and populates MediaAsset slide manifests using existing database columns.
    """
    db = SessionLocal()
    scratch_path = Path(scratch_dir)
    try:
        asset = db.get(MediaAsset, media_asset_id)
        if asset is None:
            return

        with _PRESENTATION_SEMAPHORE:
            asset.status = MediaAssetStatus.processing
            db.commit()

            try:
                input_file = Path(file_path)
                
                # Step 1: Convert PPT/PPTX to PDF
                _set_stage(db, asset, "converting")
                pdf_path = convert_presentation_to_pdf(input_file, scratch_path)

                # Step 2: Upload converted PDF to MinIO
                preview_pdf_key = f"materials/{asset.id}/preview.pdf"
                storage_service.upload_file(preview_pdf_key, str(pdf_path), "application/pdf")

                # Step 3: Extract slide images & thumbnails
                _set_stage(db, asset, "rendering")
                slide_paths, thumb_paths = extract_slide_images(pdf_path, scratch_path)

                # Step 4: Upload slide images & thumbnails to MinIO
                _set_stage(db, asset, "uploading")
                manifest = []
                for idx, (s_path, t_path) in enumerate(zip(slide_paths, thumb_paths), start=1):
                    slide_key = f"materials/{asset.id}/slides/slide_{idx:03d}.png"
                    thumb_key = f"materials/{asset.id}/thumbnails/thumb_{idx:03d}.png"

                    storage_service.upload_file(slide_key, str(s_path), "image/png")
                    storage_service.upload_file(thumb_key, str(t_path), "image/png")

                    manifest.append({
                        "slide_index": idx,
                        "slide_key": slide_key,
                        "thumbnail_key": thumb_key,
                    })

                # Persist manifest and metadata cleanly into existing schema columns:
                # - duration_seconds: stores slide_count (int)
                # - source_url: stores JSON slide manifest (text)
                # - thumbnail_object_key: stores first slide thumbnail (varchar)
                # - source_type: "presentation"
                # - source_video_id: preview_pdf_key
                asset.duration_seconds = len(manifest)
                asset.source_url = json.dumps(manifest)
                asset.source_type = "presentation"
                asset.source_video_id = preview_pdf_key
                if manifest:
                    asset.thumbnail_object_key = manifest[0]["thumbnail_key"]
                asset.status = MediaAssetStatus.ready
                asset.processing_stage = None
                asset.error_message = None
                db.commit()

            except PresentationError as exc:
                logger.warning("Presentation processing failed for asset %s: %s", media_asset_id, exc.message)
                asset.status = MediaAssetStatus.failed
                asset.processing_stage = None
                asset.error_message = exc.message
                db.commit()
            except Exception as exc:
                logger.exception("Unexpected error during presentation processing for asset %s", media_asset_id)
                asset.status = MediaAssetStatus.failed
                asset.processing_stage = None
                asset.error_message = "Failed to convert presentation to slides. You can still download the original presentation file."
                db.commit()
    finally:
        cleanup_presentation_dir(scratch_path)
        db.close()
