"""media asset nullable file fields

Revision ID: 504b58c8e13c
Revises: f22cfc7c3790
Create Date: 2026-09-06 18:48:37.680884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504b58c8e13c'
down_revision: Union[str, None] = 'f22cfc7c3790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_assets', 'object_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('media_assets', 'bucket',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('media_assets', 'mime_type',
               existing_type=sa.VARCHAR(length=127),
               nullable=True)
    op.alter_column('media_assets', 'size_bytes',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_assets', 'size_bytes',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('media_assets', 'mime_type',
               existing_type=sa.VARCHAR(length=127),
               nullable=False)
    op.alter_column('media_assets', 'bucket',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('media_assets', 'object_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###
