"""add per-app access flags to users

Revision ID: 963eda42301b
Revises: ff95d9e576b0
Create Date: 2026-09-07 13:46:01.632449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963eda42301b'
down_revision: Union[str, None] = 'ff95d9e576b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing users predate this feature and were exclusively social-media users -- backfill
    # them as such. Nobody gets smart-class access automatically; it's granted per registration.
    op.add_column('users', sa.Column('has_social_access', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('users', sa.Column('has_smart_class_access', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_smart_class_access')
    op.drop_column('users', 'has_social_access')
    # ### end Alembic commands ###
