"""add smart class library

Revision ID: f22cfc7c3790
Revises: 218acdb3de6e
Create Date: 2026-09-06 18:43:57.179256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f22cfc7c3790'
down_revision: Union[str, None] = '218acdb3de6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_chapter_class_subject_lower_name', 'chapters', ['class_id', 'subject_id', sa.text('lower(name)')], unique=True)
    op.create_table('chapter_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'part_number', name='uq_chapter_part_number')
    )
    op.create_table('learning_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order_in_part', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['chapter_parts.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.add_column with an Enum type does NOT auto-create the Postgres ENUM type the way
    # create_table does -- it must be created explicitly first.
    media_asset_status = postgresql.ENUM('pending', 'processing', 'ready', 'failed', name='mediaassetstatus')
    media_asset_status.create(op.get_bind())
    op.add_column(
        'media_assets',
        sa.Column(
            'status',
            media_asset_status,
            nullable=False,
            # Backfills existing rows (regular composer uploads, already complete) as "ready".
            server_default='ready',
        ),
    )
    op.add_column('media_assets', sa.Column('processing_stage', sa.String(length=32), nullable=True))
    op.add_column('media_assets', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('media_assets', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('media_assets', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('media_assets', sa.Column('source_type', sa.String(length=32), nullable=True))
    op.add_column('media_assets', sa.Column('source_video_id', sa.String(length=64), nullable=True))
    op.add_column('media_assets', sa.Column('thumbnail_object_key', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_media_assets_source_video_id'), 'media_assets', ['source_video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_assets_source_video_id'), table_name='media_assets')
    op.drop_column('media_assets', 'thumbnail_object_key')
    op.drop_column('media_assets', 'source_video_id')
    op.drop_column('media_assets', 'source_type')
    op.drop_column('media_assets', 'source_url')
    op.drop_column('media_assets', 'duration_seconds')
    op.drop_column('media_assets', 'error_message')
    op.drop_column('media_assets', 'processing_stage')
    op.drop_column('media_assets', 'status')
    postgresql.ENUM(name='mediaassetstatus').drop(op.get_bind())
    op.drop_table('learning_materials')
    op.drop_table('chapter_parts')
    op.drop_index('uq_chapter_class_subject_lower_name', table_name='chapters')
    op.drop_table('chapters')
    op.drop_table('subjects')
    op.drop_table('school_classes')
    # ### end Alembic commands ###
