server {
    listen 80;
    server_name newangelssocial.in www.newangelssocial.in;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 80;
    server_name files.newangelssocial.in;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name files.newangelssocial.in;

    ssl_certificate /etc/letsencrypt/live/files.newangelssocial.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/files.newangelssocial.in/privkey.pem;

    client_max_body_size 2G;

    location / {
        proxy_pass http://minio:9000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_request_buffering off;
    }
}

server {
    listen 80;
    server_name media.newangelssocial.in;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name media.newangelssocial.in;

    ssl_certificate /etc/letsencrypt/live/media.newangelssocial.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/media.newangelssocial.in/privkey.pem;

    client_max_body_size 2G;

    location / {
        proxy_pass http://minio:9001;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_buffering off;
        proxy_request_buffering off;
    }
}

server {
    listen 443 ssl;
    server_name newangelssocial.in www.newangelssocial.in;

    ssl_certificate /etc/letsencrypt/live/newangelssocial.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/newangelssocial.in/privkey.pem;

    location /api/ {
        proxy_pass http://backend:8000/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://frontend:5173;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}